export function printHelp(): void {
  const lines = [
    "chimpctl — Customer CLI for Chimpbase Cloud",
    "",
    "Usage:",
    "  chimpctl <command> [args]",
    "",
    "Auth:",
    "  login --api-url <url> --api-key <cbk_...>",
    "  logout",
    "  whoami",
    "",
    "Projects:",
    "  projects list",
    "  projects create <name>",
    "",
    "Deploy:",
    "  deploy --image <img> --name <svc> [--project <slug|id>] [--port <N>] [--replicas N]",
    "",
    "Services:",
    "  services list [--project <slug|id>]",
    "  services rm <id>",
    "",
    "Misc:",
    "  help            Show this help",
    "  version         Show chimpctl version",
    "",
    "Docs: https://chimpbase.dev/cli",
  ];
  console.log(lines.join("\n"));
}
